// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Morphware.Telepath.DataAccess;

#nullable disable

namespace Morphware.Telepath.DataAccess.Migrations
{
    [DbContext(typeof(TelepathContext))]
    partial class TelepathContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Morphware.Telepath.Core.GroupMember", b =>
                {
                    b.Property<int>("ThinkMemberId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ThinkGroupId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ThinkMemberId", "ThinkGroupId");

                    b.HasIndex("ThinkGroupId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThinkGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.ReportThought", b =>
                {
                    b.Property<int>("ReportId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ThoughtId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ReportId", "ThoughtId");

                    b.HasIndex("ThoughtId");

                    b.ToTable("ReportThoughts");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.ThinkGroup", b =>
                {
                    b.Property<int>("ThinkGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThinkGroupId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThinkGroupId");

                    b.ToTable("ThinkGroups");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.ThinkMember", b =>
                {
                    b.Property<int>("ThinkMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThinkMemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThinkMemberId");

                    b.ToTable("ThinkMembers");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.Thought", b =>
                {
                    b.Property<int>("ThoughtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThoughtId"));

                    b.Property<DateTime>("Occurred")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThinkGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ThinkMemberId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("ThoughtId");

                    b.HasIndex("TopicId");

                    b.ToTable("Thoughts");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.GroupMember", b =>
                {
                    b.HasOne("Morphware.Telepath.Core.ThinkGroup", "ThinkGroup")
                        .WithMany("GroupMembers")
                        .HasForeignKey("ThinkGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Morphware.Telepath.Core.ThinkMember", "ThinkMember")
                        .WithMany("GroupMembers")
                        .HasForeignKey("ThinkMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThinkGroup");

                    b.Navigation("ThinkMember");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.ReportThought", b =>
                {
                    b.HasOne("Morphware.Telepath.Core.Report", "Report")
                        .WithMany("ReportThoughts")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Morphware.Telepath.Core.Thought", "Thought")
                        .WithMany("ReportThoughts")
                        .HasForeignKey("ThoughtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Thought");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.Thought", b =>
                {
                    b.HasOne("Morphware.Telepath.Core.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.Report", b =>
                {
                    b.Navigation("ReportThoughts");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.ThinkGroup", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.ThinkMember", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("Morphware.Telepath.Core.Thought", b =>
                {
                    b.Navigation("ReportThoughts");
                });
#pragma warning restore 612, 618
        }
    }
}
